apiVersion: v1
kind: ReplicationController
metadata: 
  name: myjavaapp-rc
spec:
  replicas: 2
  selector:
    app: myjavaapp-rc
  
  template: 
    metadata:
      labels:
         app: myjavaapp-rc
    spec:
      containers:
      - name: myjavacontainer
        image: maha4iac
        ports:
          - containerPort: 8080
