apiVersion: v1
kind: ReplicationController
metadata: 
  name: myjavaapp-rc
spec:
  replicas: 3
  selector:
    app: myjavaapp-rc
  
  template: 
    metadata:
      labels:
         app: myjavaapp-rc
    spec:
      containers:
      - name: myjavacontainer
        image: nir321/myjavaapp14feb24
        ports:
          - containerPort: 8080
